### ISSUE TITLE
作者能否添加高赞回答至内容中

### ISSUE THREAD

**Issue by sjsdfg** [jachinlin/geektime_ebook_maker#4]
您好，感谢作者的开源分享。
我是从CSDN追过来的：https://download.csdn.net/download/jan10321/10628711
您所制作的kindle的阅读体验非常好

我看了一下其他直接使用打印另存为pdf的资料，里面的评论我觉得也很有参考价值
不知道您能不能抓取高赞的前5条数据也放在您所制作的kindle里面？

**Comment by jachinlin** [comment]
java36是这个我从其他地方找到的，所以帮不上忙。
至于添加评论，有空时会加上，或者你们提个pr

**Comment by jachinlin** [comment]
已经添加评论
